apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80        # Servisin dışarı açtığı port
      targetPort: 80  # Container’ın dinlediği port
  type: NodePort       # NodePort ile tarayıcıdan görebilirsin
